services:
  postgres:
    image: postgres:15-alpine
    container_name: skolr_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skolr_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - skolr_network
  postgres-class:
    image: postgres:15-alpine
    container_name: skolr_class_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skolr_class
    ports:
      - "5433:5432"
    volumes:
      - postgres_class_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - "skolr_network"
  auth-service:
    build:
      context: .
      dockerfile: ./packages/auth-service/Dockerfile
    container_name: skolr_auth_service
    environment:
        - NODE_PATH=/app/node_modules
        - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/skolr_auth?schema=public
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - skolr_network
  class-service:
    build:
      context: .
      dockerfile: ./packages/class-service/Dockerfile
    container_name: skolr_class_service
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-class:5432/skolr_class?schema=public
    depends_on:
      postgres-class:
        condition: service_healthy
    networks:
      - skolr_network
  gateway:
    build:
      context: ./packages/gateway
      dockerfile: Dockerfile
    container_name: skolr_gateway
    environment:
      - PORT=3001
      - AUTH_SERVICE_URL=http://auth-service:3000
      - CLASS_SERVICE_URL=http://class-service:3002
    ports:
      - "3001:3001"
    depends_on:
      - auth-service
    networks:
      - skolr_network

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: skolr_frontend
    volumes:
      - ./packages/frontend:/app
    environment:
      - NODE_ENV=development
      - NUXT_PUBLIC_GATEWAY_BASE_URL=/api
      - GATEWAY_INTERNAL_URL=http://gateway:3001
    command: bun run dev --host 0.0.0.0 --port 3003
    ports:
      - "3003:3003"
    depends_on:
      - gateway
    networks:
      - skolr_network
volumes:
  postgres_auth_data:
  postgres_class_data:

networks:
  skolr_network:
    driver: bridge
