services:
  postgres:
    image: postgres:15-alpine
    container_name: skolr_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skolr_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - skolr_network
  postgres-class:
    image: postgres:15-alpine
    container_name: skolr_class_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skolr_class
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - "skolr_network"
  auth-service:
    build:
      context: .
      dockerfile: ./packages/auth-service/Dockerfile
    container_name: skolr_auth_service
    environment:
        - NODE_PATH=/app/node_modules
        - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/skolr_auth?schema=public
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - skolr_network
  gateway:
    build:
      context: ./packages/gateway
      dockerfile: Dockerfile
    container_name: skolr_gateway
    ports:
      - "3001:3001"
    # depends_on:
    #   - auth-service
    networks:
      - skolr_network
volumes:
  postgres_data:

networks:
  skolr_network:
    driver: bridge
