name: Auth Service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'packages/auth-service/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'packages/auth-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install

    - name: Generate Prisma client
      working-directory: packages/auth-service
      run: bunx prisma generate

    - name: Build auth-service
      working-directory: packages/auth-service
      run: bun run build

    # - name: Test auth-service
    #   working-directory: packages/auth-service
    #   run: bun test
