name: Gateway CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'packages/gateway/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'packages/gateway/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2


    - name: Install dependencies
      run: bun install

    - name: Build gateway
      working-directory: packages/gateway
      run: bun run build

    # - name: Test gateway
    #   working-directory: packages/gateway
    #   run: bun test
